import type { Metadata } from "next";
import "./globals.css";
import { Dosis } from "next/font/google";
import Image from "next/image";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "habits App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body
        className={`${dosis.className} flex items-center flex-col mt-10 bg-nutral-900`}
      >
        <Image src="/images/logo.svg" width={200} height={200} alt="logo" />
        {children}
      </body>
    </html>
  );
}
